# Generated by Django 4.2.13 on 2024-07-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginformation',
            name='email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='first_name',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='last_name',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
