# Generated by Django 4.2.13 on 2024-07-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_information', '0002_alter_shippinginformation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginformation',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
