# Generated by Django 4.2.13 on 2024-07-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_information', '0003_alter_shippinginformation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginformation',
            name='address_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
