# Generated by Django 4.2.13 on 2024-06-03 17:02

from django.db import migrations, models
import django.db.models.deletion
import thumbnails.fields
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', thumbnails.fields.ImageField(blank=True, null=True, upload_to='category')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='KindProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('principal_image', thumbnails.fields.ImageField(blank=True, null=True, upload_to='kind')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kinds', to='product.category')),
            ],
            options={
                'verbose_name': 'Kind',
                'verbose_name_plural': 'Kinds',
            },
        ),
        migrations.CreateModel(
            name='SubKindProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subkinds', to='product.kindproduct')),
            ],
            options={
                'verbose_name': 'SubKind',
                'verbose_name_plural': 'SubKinds',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, max_length=400, null=True)),
                ('short_description', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('description', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('views', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('image_principal', thumbnails.fields.ImageField(blank=True, null=True, upload_to='product')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='product.category')),
                ('kind_of_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_kind', to='product.kindproduct')),
                ('sub_kind_of_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_subkind', to='product.subkindproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
