# Generated by Django 4.2.13 on 2024-06-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kindproduct',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Kind', 'verbose_name_plural': 'Kinds'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
