# Generated by Django 4.2.13 on 2024-06-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_slug_alter_kindproduct_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_presale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
