# Generated by Django 4.2.13 on 2024-06-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_is_presale_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subkindproduct',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
