# Generated by Django 4.2.13 on 2024-06-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_subkindproduct_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subkindproduct',
            unique_together={('kind', 'name')},
        ),
    ]
