# Generated by Django 4.2.13 on 2024-06-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_subkindproduct_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_product_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
