# Generated by Django 4.2.13 on 2024-06-24 19:47

from django.db import migrations, models
import django.db.models.deletion
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_is_product_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('principal_image', thumbnails.fields.ImageField(blank=True, null=True, upload_to='product/kind/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='product.category')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='subkindproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subkindproduct',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kind_of_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_kind_of_product',
        ),
        migrations.DeleteModel(
            name='KindProduct',
        ),
        migrations.DeleteModel(
            name='SubKindProduct',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sub_category', to='product.subcategory'),
        ),
    ]
