# Generated by Django 4.2.13 on 2024-06-04 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_kindproduct_options_alter_product_options'),
        ('product_vendor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvendor',
            options={},
        ),
        migrations.RemoveField(
            model_name='productvendor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productvendor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productvendor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productvendor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productvendor',
            name='image_principal',
        ),
        migrations.RemoveField(
            model_name='productvendor',
            name='kind_of_product',
        ),
        migrations.RemoveField(
            model_name='productvendor',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='productvendor',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='productvendor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productvendor',
            name='sub_kind_of_product',
        ),
        migrations.RemoveField(
            model_name='productvendor',
            name='title',
        ),
        migrations.RemoveField(
            model_name='productvendor',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productvendor',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='productvendor',
            name='views',
        ),
        migrations.AddField(
            model_name='productvendor',
            name='days_to_deliver',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvendor',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default='2', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product'),
            preserve_default=False,
        ),
    ]
