# Generated by Django 4.2.13 on 2024-06-04 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_vendor', '0002_alter_productvendor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvendor',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Product Vendor', 'verbose_name_plural': 'Products Vendor'},
        ),
        migrations.RemoveField(
            model_name='productvendor',
            name='days_to_deliver',
        ),
        migrations.AddField(
            model_name='productvendor',
            name='days_in_publication',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='productvendor',
            name='last_date_in_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvendor',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
