# Generated by Django 4.2.13 on 2024-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_vendor', '0003_alter_productvendor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvendor',
            name='last_date_in_publication',
            field=models.DateField(blank=True, null=True),
        ),
    ]
