# Generated by Django 4.2.13 on 2024-06-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_vendor', '0004_alter_productvendor_last_date_in_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvendor',
            name='last_date_in_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
