# Generated by Django 4.2.13 on 2024-06-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_vendor', '0005_alter_productvendor_last_date_in_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvendor',
            name='days_in_publication',
            field=models.IntegerField(choices=[(30, '30'), (60, '60')], default=30),
        ),
    ]
