# Generated by Django 4.2.13 on 2024-06-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_vendor', '0006_alter_productvendor_days_in_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvendor',
            name='is_product_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
