# Generated by Django 4.2.13 on 2024-06-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_vendor', '0007_productvendor_is_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvendor',
            name='is_product_vendor',
        ),
    ]
